FROM golang:1.17.2 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build ./cmd/server

FROM gcr.io/distroless/static
WORKDIR /app
COPY --from=builder /app/server .
CMD ["/app/server"]
